/// Country + nationality reference list used by the director-details
/// pickers. Curated to ~120 entries — enough coverage for UK Companies
/// House director declarations without bundling the full ISO 3166 set.
class Country {
  /// Common name used as the country-of-residence label.
  final String name;
  /// Adjectival form used as nationality (e.g. "British", "French").
  final String nationality;
  /// ISO 3166-1 alpha-2 code.
  final String code;

  const Country(this.name, this.nationality, this.code);
}

const List<Country> kCountries = [
  Country('United Kingdom', 'British', 'GB'),
  Country('Ireland', 'Irish', 'IE'),
  Country('United States', 'American', 'US'),
  Country('France', 'French', 'FR'),
  Country('Germany', 'German', 'DE'),
  Country('Italy', 'Italian', 'IT'),
  Country('Spain', 'Spanish', 'ES'),
  Country('Portugal', 'Portuguese', 'PT'),
  Country('Netherlands', 'Dutch', 'NL'),
  Country('Belgium', 'Belgian', 'BE'),
  Country('Luxembourg', 'Luxembourgish', 'LU'),
  Country('Switzerland', 'Swiss', 'CH'),
  Country('Austria', 'Austrian', 'AT'),
  Country('Denmark', 'Danish', 'DK'),
  Country('Sweden', 'Swedish', 'SE'),
  Country('Norway', 'Norwegian', 'NO'),
  Country('Finland', 'Finnish', 'FI'),
  Country('Iceland', 'Icelandic', 'IS'),
  Country('Poland', 'Polish', 'PL'),
  Country('Czech Republic', 'Czech', 'CZ'),
  Country('Slovakia', 'Slovak', 'SK'),
  Country('Hungary', 'Hungarian', 'HU'),
  Country('Romania', 'Romanian', 'RO'),
  Country('Bulgaria', 'Bulgarian', 'BG'),
  Country('Greece', 'Greek', 'GR'),
  Country('Cyprus', 'Cypriot', 'CY'),
  Country('Malta', 'Maltese', 'MT'),
  Country('Croatia', 'Croatian', 'HR'),
  Country('Slovenia', 'Slovenian', 'SI'),
  Country('Serbia', 'Serbian', 'RS'),
  Country('Bosnia and Herzegovina', 'Bosnian', 'BA'),
  Country('Albania', 'Albanian', 'AL'),
  Country('Estonia', 'Estonian', 'EE'),
  Country('Latvia', 'Latvian', 'LV'),
  Country('Lithuania', 'Lithuanian', 'LT'),
  Country('Russia', 'Russian', 'RU'),
  Country('Ukraine', 'Ukrainian', 'UA'),
  Country('Belarus', 'Belarusian', 'BY'),
  Country('Moldova', 'Moldovan', 'MD'),
  Country('Georgia', 'Georgian', 'GE'),
  Country('Armenia', 'Armenian', 'AM'),
  Country('Azerbaijan', 'Azerbaijani', 'AZ'),
  Country('Kazakhstan', 'Kazakh', 'KZ'),
  Country('Uzbekistan', 'Uzbek', 'UZ'),
  Country('Turkey', 'Turkish', 'TR'),
  Country('Israel', 'Israeli', 'IL'),
  Country('United Arab Emirates', 'Emirati', 'AE'),
  Country('Saudi Arabia', 'Saudi', 'SA'),
  Country('Qatar', 'Qatari', 'QA'),
  Country('Kuwait', 'Kuwaiti', 'KW'),
  Country('Bahrain', 'Bahraini', 'BH'),
  Country('Oman', 'Omani', 'OM'),
  Country('Jordan', 'Jordanian', 'JO'),
  Country('Lebanon', 'Lebanese', 'LB'),
  Country('Egypt', 'Egyptian', 'EG'),
  Country('Morocco', 'Moroccan', 'MA'),
  Country('Tunisia', 'Tunisian', 'TN'),
  Country('Algeria', 'Algerian', 'DZ'),
  Country('South Africa', 'South African', 'ZA'),
  Country('Nigeria', 'Nigerian', 'NG'),
  Country('Kenya', 'Kenyan', 'KE'),
  Country('Ghana', 'Ghanaian', 'GH'),
  Country('Ethiopia', 'Ethiopian', 'ET'),
  Country('India', 'Indian', 'IN'),
  Country('Pakistan', 'Pakistani', 'PK'),
  Country('Bangladesh', 'Bangladeshi', 'BD'),
  Country('Sri Lanka', 'Sri Lankan', 'LK'),
  Country('Nepal', 'Nepali', 'NP'),
  Country('China', 'Chinese', 'CN'),
  Country('Hong Kong', 'Hong Konger', 'HK'),
  Country('Taiwan', 'Taiwanese', 'TW'),
  Country('Japan', 'Japanese', 'JP'),
  Country('South Korea', 'South Korean', 'KR'),
  Country('Singapore', 'Singaporean', 'SG'),
  Country('Malaysia', 'Malaysian', 'MY'),
  Country('Indonesia', 'Indonesian', 'ID'),
  Country('Thailand', 'Thai', 'TH'),
  Country('Vietnam', 'Vietnamese', 'VN'),
  Country('Philippines', 'Filipino', 'PH'),
  Country('Australia', 'Australian', 'AU'),
  Country('New Zealand', 'New Zealander', 'NZ'),
  Country('Canada', 'Canadian', 'CA'),
  Country('Mexico', 'Mexican', 'MX'),
  Country('Brazil', 'Brazilian', 'BR'),
  Country('Argentina', 'Argentine', 'AR'),
  Country('Chile', 'Chilean', 'CL'),
  Country('Colombia', 'Colombian', 'CO'),
  Country('Peru', 'Peruvian', 'PE'),
  Country('Venezuela', 'Venezuelan', 'VE'),
  Country('Uruguay', 'Uruguayan', 'UY'),
  Country('Ecuador', 'Ecuadorian', 'EC'),
];
